jwt:
  secret: dafasfasdf55adf
  expires: 7

server:
  port: 6710

spring:
  application:
    name: charger-gateway
  profiles:
    # 必须在这里配置，不然无法从配置中心获取信息
    active: dev
  config:
    import: 'configserver:'
  boot:
    admin:
      client:
        url: http://${CLOUD_HOST}:6700/app-monitor
        instance:
          health-url: http://${CLOUD_HOST}:6710
  cloud:
    config:
      discovery:
        enabled: true
        service-id: charger-config
    gateway:
      discovery:
        locator:
          enabled: true # 是否和服务注册与发现组件结合，设置为 true 后可以直接使用应用名称调用服务
          lower-case-service-id: true
      routes:
        - id: iot
          predicates:
            - Path=/test/**
              Host="**.abc.org"
          uri: http://www.baidu.com
          filters:
            - StripPrefix= 1 #过滤几个前缀/为间隔
            - AddResponseHeader="X-TestHeader",foobar
        - id: api-user
          predicates:
            - Path=/api/user/**
          uri: lb://charger-consumer-user

# 运行监控相关的配置
management:
  health:
    diskspace:
      enabled: true
    db:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

# 配置集群eureka注册中心
eureka:
  instance:
    hostname: ${CLOUD_HOST}
    instance-id: ${CLOUD_HOST}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${CLOUD_HOST}:8761/eureka/

# 日志
logging:
  file:
    name: logs/charger_gateway.log
  level:
    com.phynos.charger: DEBUG
    com:
      spring: trace
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%t]){faint} %clr(%-40.40logger{39}){cyan}[lineno:%line]    %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%t] %-40.40logger{39}[lineno:%line]: %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  logback:
    rollingpolicy:
      max-file-size: 300MB
      max-history: 15