spring:
  application:
    name: charger-product-sys
  profiles:
    active: dev

server:
  port: 6801

eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


config:
  product:
    sys:
      username: NaN
      password: NaN

