
server:
  port: ${APP_PORT} #6801 ~ 6809

spring:
  application:
    name: charger_product_sys
  profiles:
    active: dev
  cloud:
    config:
      #uri: http://localhost:6300
      # 从注册中心获取配置中心的服务
      discovery:
        enabled: true
        service-id: charger_config
      label: master
      profile: dev

eureka:
  instance:
    hostname: ${CLOUD_HOST}
    instance-id: ${CLOUD_HOST}:${server.port}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${CLOUD_HOST}:8761/eureka/

config:
  product:
    sys:
      username: NaN
      password: NaN

