server:
  port: 6901

spring:
  application:
    name: spring-cloud-consumer-user
  cloud:
    config:
      uri: http://localhost:6300 #配置中心地址

# 在feign中开启熔断器
feign:
  hystrix:
    enabled: true


# 配置集群eureka注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
