server:
  port: 6001

spring:
  application:
    name: spring-cloud-consumer-user

# 在feign中开启熔断器
feign:
  hystrix:
    enabled: true


# 配置集群eureka注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
