version: '3'
services:
  charger-monitor:
    build:
      context: ./charger-monitor
    image: charger_monitor
    container_name: charger_monitor
    restart: always
    volumes:
      - /home/lupc/tink/charger:/cloud/logs
    ports:
      - 6700:6700
    environment:
      CLOUD_HOST: ${CLOUD_HOST}

  charger-eureka:
    build:
      context: ./charger-eureka
    image: charger_eureka
    container_name: charger_eureka
    restart: always
    volumes:
      - /home/lupc/tink/charger:/cloud/logs
    ports:
      - 8761:8761
    environment:
      CLOUD_HOST: ${CLOUD_HOST}

  charger-config:
    build:
      context: ./charger-config
    image: charger_config
    container_name: charger_config
    depends_on:
      - charger-eureka
    restart: always
    volumes:
      - /home/lupc/tink/charger:/cloud/logs
    ports:
      - 6720:6720
    environment:
      CLOUD_HOST: ${CLOUD_HOST}

  charger-gateway:
    build:
      context: ./charger-gateway
    image: charger_gateway
    container_name: charger_gateway
    depends_on:
      - charger-config
      - charger-monitor
      - charger-eureka
    restart: always
    volumes:
      - /home/lupc/tink/charger:/cloud/logs
    ports:
      - 6710:6710
    environment:
      CLOUD_HOST: ${CLOUD_HOST}

  charger-auth:
    build:
      context: ./charger-auth
    image: charger_auth
    container_name: charger_auth
    depends_on:
      - charger-config
      - charger-monitor
      - charger-eureka
    restart: always
    volumes:
      - /home/lupc/tink/charger:/cloud/logs
    ports:
      - 6730:6730
    environment:
      CLOUD_HOST: ${CLOUD_HOST}

  charger-product-sys:
    build:
      context: ./charger-product/charger-product-sys
    image: charger_product_sys
    container_name: charger_product_sys
    depends_on:
      - charger-config
      - charger-monitor
      - charger-eureka
    restart: always
    volumes:
      - /home/lupc/tink/charger:/cloud/logs
    ports:
      - 6801:6801
    environment:
      CLOUD_HOST: ${CLOUD_HOST}
      APP_PORT: 6801

  charger-product-user-1:
    build:
      context: ./charger-product/charger-product-user
    image: charger_product_user
    container_name: charger_product_user_1
    depends_on:
      - charger-config
      - charger-monitor
      - charger-eureka
    restart: always
    volumes:
      - /home/lupc/tink/charger/product_1:/cloud/logs
    ports:
      - 6811:6811
    environment:
      CLOUD_HOST: ${CLOUD_HOST}
      APP_PORT: 6811

  charger-product-user-2:
    image: charger_product_user
    container_name: charger_product_user_2
    depends_on:
      - charger-config
      - charger-monitor
      - charger-eureka
    restart: always
    volumes:
      - /home/lupc/tink/charger/product_2:/cloud/logs
    ports:
      - 6812:6812
    environment:
      CLOUD_HOST: ${CLOUD_HOST}
      APP_PORT: 6812

  charger-consumer-user-1:
    build:
      context: ./charger-consumer/charger-consumer-user
    image: charger_consumer_user
    container_name: charger_consumer_user_1
    depends_on:
      - charger-config
      - charger-monitor
      - charger-eureka
    restart: always
    volumes:
      - /home/lupc/tink/charger/consumer_1:/cloud/logs
    ports:
      - 6901:6901
    environment:
      CLOUD_HOST: ${CLOUD_HOST}
      APP_PORT: 6901

  charger-consumer-user-2:
    image: charger_consumer_user
    container_name: charger_consumer_user_2
    depends_on:
      - charger-config
      - charger-monitor
      - charger-eureka
    restart: always
    volumes:
      - /home/lupc/tink/charger/consumer_2:/cloud/logs
    ports:
      - 6902:6902
    environment:
      CLOUD_HOST: ${CLOUD_HOST}
      APP_PORT: 6902
