version: '3'
services:
  phynos-mysql:
    build:
      context: ./db
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    container_name: phynos-mysql
    image: phynos-mysql
    ports:
      - 3306:3306

  phynos-redis:
    image: redis:6.0
    ports:
      - 6379:6379
    restart: always
    container_name: phynos-redis
    hostname: phynos-redis

  phynos-monitor:
    build:
      context: ./phynos-monitor
    restart: always
    ports:
      - 6000:6000
    container_name: phynos-monitor
    hostname: phynos-monitor
    image: phynos-monitor

  phynos-cloud-eureka:
    build:
      context: ./phynos-cloud-eureka
    restart: always
    ports:
      - 8761:8761
    container_name: phynos-cloud-eureka
    hostname: phynos-cloud-eureka
    image: phynos-cloud-eureka

  phynos-cloud-config:
    build:
      context: ./phynos-cloud-config
    restart: always
    ports:
      - 6300:6300
    container_name: phynos-cloud-config
    hostname: phynos-cloud-config
    image: phynos-cloud-config

  phynos-cloud-gateway:
    build:
      context: ./phynos-cloud-gateway
    restart: always
    ports:
      - 6100:6100
    container_name: phynos-cloud-gateway
    hostname: phynos-cloud-gateway
    image: phynos-cloud-gateway

  phynos-auth:
    build:
      context: ./phynos-cloud-auth
    restart: always
    ports:
      - 6400:6400
    container_name: phynos-auth
    hostname: phynos-auth
    image: phynos-auth

  phynos-cloud-product-sys:
    build:
      context: ./phynos-cloud-product/phynos-cloud-product-sys
    restart: always
    ports:
      - 6801:6801
    container_name: phynos-cloud-product-sys
    hostname: phynos-cloud-product-sys
    image: phynos-cloud-product-sys

  phynos-cloud-product-user:
    build:
      context: ./phynos-cloud-product/phynos-cloud-product-user
    restart: always
    ports:
      - 6802:6802
    container_name: phynos-cloud-product-user
    hostname: phynos-cloud-product-user
    image: phynos-cloud-product-user

  phynos-cloud-consumer-user:
    build:
      context: ./phynos-cloud-consumer/phynos-cloud-consumer-user
    restart: always
    ports:
      - 6901:6901
    container_name: phynos-cloud-consumer-user
    hostname: phynos-cloud-consumer-user
    image: phynos-cloud-consumer-user

