version: '3'
services:
  charger-monitor:
    build:
      context: ./charger-monitor
    image: charger_monitor
    container_name: charger_monitor
    restart: always
    volumes:
      - /home/lupc/tink/charger:/cloud/logs
    ports:
      - 6700:6700

  charger-eureka:
    build:
      context: ./charger-eureka
    image: charger_eureka
    container_name: charger_eureka
    restart: always
    volumes:
      - /home/lupc/tink/charger:/cloud/logs
    ports:
      - 8761:8761

  charger-config:
    build:
      context: ./charger-config
    image: charger_config
    container_name: charger_config
    restart: always
    volumes:
      - /home/lupc/tink/charger:/cloud/logs
    ports:
      - 6720:6720

  charger-gateway:
    build:
      context: ./charger-gateway
    image: charger_gateway
    container_name: charger_gateway
    restart: always
    volumes:
      - /home/lupc/tink/charger:/cloud/logs
    ports:
      - 6710:6710