version: '3'
services:
  charger-monitor:
    build:
      context: ./charger-monitor
    image: charger/monitor
    container_name: charger_monitor
    logging:
      options:
        max-size: "50m"
    restart: always
    volumes:
      - /home/lupc/tink/charger:/cloud/logs
    ports:
      - "6700:6700"
    environment:
      CLOUD_HOST: ${CLOUD_HOST}

  charger-eureka:
    build:
      context: ./charger-eureka
    image: charger/eureka
    container_name: charger_eureka
    logging:
      options:
        max-size: "50m"
    restart: always
    volumes:
      - /home/lupc/tink/charger:/cloud/logs
    ports:
      - "8761:8761"
    environment:
      CLOUD_HOST: ${CLOUD_HOST}

  charger-config:
    build:
      context: ./charger-config
    image: charger/config
    container_name: charger_config
    logging:
      options:
        max-size: "50m"
    depends_on:
      - charger-eureka
    restart: always
    volumes:
      - /home/lupc/tink/charger:/cloud/logs
    ports:
      - "6720:6720"
    environment:
      CLOUD_HOST: ${CLOUD_HOST}

  charger-gateway:
    build:
      context: ./charger-gateway
    image: charger/gateway
    container_name: charger_gateway
    deploy:
      resources:
        limits:
          cpus: 4 #限制CPU最多6核心
    logging:
      options:
        max-size: "50m"
    depends_on:
      - charger-config
      - charger-monitor
      - charger-eureka
    restart: always
    volumes:
      - /home/lupc/tink/charger:/cloud/logs
    ports:
      - "6710:6710"
    environment:
      CLOUD_HOST: ${CLOUD_HOST}

  charger-auth:
    build:
      context: ./charger-auth
    image: charger/auth
    container_name: charger_auth
    logging:
      options:
        max-size: "50m"
    depends_on:
      - charger-config
      - charger-monitor
      - charger-eureka
    restart: always
    volumes:
      - /home/lupc/tink/charger:/cloud/logs
    ports:
      - "6730:6730"
    environment:
      CLOUD_HOST: ${CLOUD_HOST}

  charger-nginx:
    image: nginx:latest
    container_name: charger_nginx
    logging:
      options:
        max-size: "50m"
    depends_on:
      - charger-auth
      - charger-gateway
    restart: always
    volumes:
      - /home/lupc/tink/charger/nginx/conf.d:/etc/nginx/conf.d
      - /home/lupc/tink/charger/nginx/log:/var/log/nginx
      - /home/lupc/tink/charger/nginx/html:/var/nginx/html
      - /etc/localtime:/etc/localtime
    ports:
      - "6701:80"
    environment:
      CLOUD_HOST: ${CLOUD_HOST}
