spring:
  application:
    name: charger-product-user

server:
  port: 6811

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

config:
  product:
    user:
      username: NaN
      password: NaN
