spring:
  application:
    name: charger-product-user

server:
  port: 6811

eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

config:
  product:
    user:
      username: NaN
      password: NaN
