server:
  port: 6811

spring:
  application:
    name: charger-product-user
  profiles:
    # 必须在这里配置，不然无法从配置中心获取信息
    active: dev
  cloud:
    config:
      #uri: http://localhost:6300
      # 从注册中心获取配置中心的服务
      discovery:
        enabled: true
        service-id: charger-config
      label: master
      profile: dev

eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

config:
  product:
    user:
      username: NaN
      password: NaN
