server:
  port: ${APP_PORT} #6811 ~ 6819

spring:
  application:
    name: charger_product_user
  profiles:
    # 必须在这里配置，不然无法从配置中心获取信息
    active: dev
  boot:
    admin:
      client:
        url: http://${CLOUD_HOST}:6700/app-monitor        
  cloud:
    config:
      #uri: http://localhost:6300
      # 从注册中心获取配置中心的服务
      discovery:
        enabled: true
        service-id: charger_config
      label: master
      profile: dev

eureka:
  instance:
    hostname: ${CLOUD_HOST}
    instance-id: ${CLOUD_HOST}:${server.port}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${CLOUD_HOST}:8761/eureka/

config:
  product:
    user:
      username: NaN
      password: NaN

# 运行监控相关的配置
management:
  health:
    diskspace:
      enabled: true
    db:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

# 日志
logging:
  file:
    name: logs/charger-product-user-${server.port}.log
  level:
    com.phynos.charger: DEBUG
    com:
      spring: trace
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%t]){faint} %clr(%-40.40logger{39}){cyan}[lineno:%line]    %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%t] %-40.40logger{39}[lineno:%line]: %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"