server:
  port: ${APP_PORT} #6811 ~ 6819

spring:
  application:
    name: charger_product_user
  profiles:
    # 必须在这里配置，不然无法从配置中心获取信息
    active: dev
  cloud:
    config:
      #uri: http://localhost:6300
      # 从注册中心获取配置中心的服务
      discovery:
        enabled: true
        service-id: charger_config
      label: master
      profile: dev

eureka:
  instance:
    hostname: ${CLOUD_HOST}
    instance-id: ${CLOUD_HOST}:${server.port}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${CLOUD_HOST}:8761/eureka/

config:
  product:
    user:
      username: NaN
      password: NaN
