spring:
  application:
    name: spring-cloud-product-sys
  profiles:
    active: dev

server:
  port: 6802

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


config:
  product:
    sys:
      username: NaN
      password: NaN

