server:
  port: 6999

spring:
  application:
    name: phynos-cloud-config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///user/config/abc

