version: '3.0'
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
    restart: always
    command: server /data
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: ${PASSWORD} #大于等于8位，命令行传入
    logging:
      options:
        max-size: "50M" # 最大文件上传限制
        max-file: "10"
      driver: json-file
    volumes:
      - /home/lupc/tink/minio/data:/data #数据文件
      - /home/lupc/tink/minio/config:/root/.minio #配置文件