version: '3'
services:
  charger-mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: always
    privileged: true
    ports:
      - 1883:1883
    volumes:
      - /home/lupc/tink/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /home/lupc/tink/mosquitto/data:/mosquitto/data
      - /home/lupc/tink/mosquitto/log:/mosquitto/log