version: '3'
services:
  charger-mysql:
    image: mysql:latest
    container_name: charger-mysql
    hostname: localhost
    network_mode: bridge
    environment:
      MYSQL_ROOT_PASSWORD: xxxx
    restart: always
    ports:
      - 3306:3306
    volumes:
      # - /home/lupc/tink/mysql:/var/lib/mysql
      - /home/lupc/tink/mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf