version: '3'
services:
  charger-rabbitmq:
    image: rabbitmq
    container_name: charger-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: ${PASSWORD}
    restart: always
    ports:
      - 5672:5672
      - 15672:15672