
spring:
  application:
    name: phynos-cloud-monitor
  boot:
    admin:
      ui:
        title: '微服务后台监控'

server:
  port: 6666
  servlet:
    context-path: /app-monitor

management:
  endpoints:
    web:
      base-path: '/actuator'
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

