server:
  port: ${APP_PORT} # 6901~6909
  servlet:
    context-path: /api/user
spring:
  application:
    name: charger_consumer_user
  profiles:
    active: dev
  cloud:
    config:
      #uri: http://localhost:6300
      # 从注册中心获取配置中心的服务
      discovery:
        enabled: true
        service-id: charger_config
      label: master
      profile: dev

# 在feign中开启熔断器
feign:
  circuitbreaker:
    enabled: true

# 配置集群eureka注册中心
eureka:
  instance:
    hostname: ${CLOUD_HOST}
    instance-id: ${CLOUD_HOST}:${server.port}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${CLOUD_HOST}:8761/eureka/
