server:
  port: 6730

spring:
  application:
    name: charger-auth #名称不能使用下划线，否则gateway无法使用
  profiles:
    # 必须在这里配置，不然无法从配置中心获取信息
    active: dev
  boot:
    admin:
      client:
        url: http://${CLOUD_HOST}:6700/app-monitor
  cloud:
    config:
      #uri: http://localhost:6300
      # 从注册中心获取配置中心的服务
      discovery:
        enabled: true
        service-id: charger-config
      label: master
      profile: prod

# 配置集群eureka注册中心
eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${CLOUD_HOST}:8761/eureka/

# 运行监控相关的配置
management:
  health:
    diskspace:
      enabled: true
    db:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

# 日志
logging:
  config: classpath:logback-spring.xml