spring:
  application:
    name: phynos-cloud-zipkin-service

server:
  port: 6200

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false