spring:
  application:
    name: spring-cloud-zipkin-service

server:
  port: 6200

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:6000/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false