server:
  port: 6720

spring:
  application:
    name: charger_config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config

# 配置集群eureka注册中心
eureka:
  instance:
    hostname: ${CLOUD_HOST}
    instance-id: ${CLOUD_HOST}:${server.port}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${CLOUD_HOST}:8761/eureka/

# 日志
logging:
  file:
    name: logs/charger_config.log
  level:
    com.phynos.charger: DEBUG
    com:
      spring: trace
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%t]){faint} %clr(%-40.40logger{39}){cyan}[lineno:%line]    %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%t] %-40.40logger{39}[lineno:%line]: %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"