server:
  port: 6300

spring:
  application:
    name: spring-cloud-config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config

# 配置集群eureka注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

